package com.example.recipe_app_compose.ui.theme

import androidx.compose.ui.graphics.Color

// Warm, food-inspired brand colors shared by every Compose host.
// Semantic usage is assigned in Theme.kt so screens do not depend on raw colors.
val primaryLight = Color(0xFF9B2F23)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDAD2)
val onPrimaryContainerLight = Color(0xFF3B0803)
val secondaryLight = Color(0xFF606042)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE6E4BF)
val onSecondaryContainerLight = Color(0xFF1D1D07)
val tertiaryLight = Color(0xFF8A5A00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDDB0)
val onTertiaryContainerLight = Color(0xFF2C1700)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFFBF7)
val onBackgroundLight = Color(0xFF211A18)
val surfaceLight = Color(0xFFFFFBF7)
val onSurfaceLight = Color(0xFF211A18)
val surfaceVariantLight = Color(0xFFF2DED8)
val onSurfaceVariantLight = Color(0xFF52443F)
val outlineLight = Color(0xFF85736D)
val outlineVariantLight = Color(0xFFD7C2BA)
val inverseSurfaceLight = Color(0xFF362F2D)
val inverseOnSurfaceLight = Color(0xFFFBEEEA)
val inversePrimaryLight = Color(0xFFFFB4A8)
val surfaceDimLight = Color(0xFFE4D7D2)
val surfaceBrightLight = Color(0xFFFFFBF7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF3EC)
val surfaceContainerLight = Color(0xFFFCEDE5)
val surfaceContainerHighLight = Color(0xFFF6E7DF)
val surfaceContainerHighestLight = Color(0xFFF0E1D9)

val primaryDark = Color(0xFFFFB4A8)
val onPrimaryDark = Color(0xFF5F150D)
val primaryContainerDark = Color(0xFF7D2118)
val onPrimaryContainerDark = Color(0xFFFFDAD2)
val secondaryDark = Color(0xFFCAC8A4)
val onSecondaryDark = Color(0xFF313117)
val secondaryContainerDark = Color(0xFF48482B)
val onSecondaryContainerDark = Color(0xFFE6E4BF)
val tertiaryDark = Color(0xFFFFB95C)
val onTertiaryDark = Color(0xFF492900)
val tertiaryContainerDark = Color(0xFF693D00)
val onTertiaryContainerDark = Color(0xFFFFDDB0)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF181211)
val onBackgroundDark = Color(0xFFF0DED8)
val surfaceDark = Color(0xFF181211)
val onSurfaceDark = Color(0xFFF0DED8)
val surfaceVariantDark = Color(0xFF52443F)
val onSurfaceVariantDark = Color(0xFFD7C2BA)
val outlineDark = Color(0xFFA08C85)
val outlineVariantDark = Color(0xFF52443F)
val inverseSurfaceDark = Color(0xFFF0DED8)
val inverseOnSurfaceDark = Color(0xFF362F2D)
val inversePrimaryDark = Color(0xFF9B2F23)
val surfaceDimDark = Color(0xFF181211)
val surfaceBrightDark = Color(0xFF403735)
val surfaceContainerLowestDark = Color(0xFF110D0C)
val surfaceContainerLowDark = Color(0xFF211A18)
val surfaceContainerDark = Color(0xFF251E1C)
val surfaceContainerHighDark = Color(0xFF302826)
val surfaceContainerHighestDark = Color(0xFF3B322F)
